version: "3.8"
volumes:
  cert:
  php-fpm-socket:
  db-store:
  cache:
services:
  # php
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}

  #nginx
  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
      - '443:443'
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./backend:/work/backend
      - cert:/etc/ssl/private

  # mariadb
  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}

  # redis 5.0
  redis:
    image: "redis:5.0"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"

  # node(v10.17) js (include gulp(v3.9.1))
  # node:
  #   build: ./infra/docker/node/Dockerfile
  #   tty: true
  #   ports:
  #     - '8081'
  #   depends_on:
  #     - web
  #   volumes:
  #     - ./backend:/work/backend

  # phpMyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - 8080:80